#ifndef _MESSAGE_TYPES_H_
#define _MESSAGE_TYPES_H_

enum MessageListType
{
	INPUT_MOUSE_POSITION = 0,
	INPUT_MOUSE_DOWN,
	INPUT_MOUSE_CLICK,
	INPUT_MOUSE_RELEASE,
	INPUT_MOUSE_ALL,

	INPUT_BUTTON_HOLD_IN,
	INPUT_BUTTON_CLICKED,
	INPUT_BUTTON_RELEASED,

	NUM_OF_MESSAGE_TYPES
};

#endif